# Generated by Django 4.2.16 on 2024-11-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("codigo", models.IntegerField(default=0)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="tarefas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.IntegerField(default=0)),
                ("descricao", models.CharField(max_length=100)),
                ("setor", models.CharField(max_length=100)),
                ("prioridade", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("data", models.DateField()),
                (
                    "usu_codigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Atividade.usuarios",
                    ),
                ),
            ],
        ),
    ]
