# Generated by Django 5.1.2 on 2024-11-22 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='prioridade',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Fazendo', 'Fazendo'), ('Concluído', 'Concluído')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='usu_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='Atividade.usuarios'),
        ),
    ]
